baseURL: https://www.destinysartistry.com/
languageCode: en-us
title: "Destiny's Artistry"
theme: "PaperMod"

params:
  ShowDateOnPosts: false
menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: contact
      name: contact
      url: /contact/
      weight: 20
    